### PR TITLE
Show created timestamp on ownership_list plugin page

### PR DESCRIPTION
**Pull request by ChemiKyle**
Old:

image

New:

image

### CODE REVIEW

**Comment by tlstoffs** [comment]
looks good!

**Comment by pbchase** [comment]
@ChemiKyle, you added "created", but we wanted "creation_time" from the redcap_projects table. I added it in my last commit.

I know we did not request it, but can you dumb down the searching of the Project field. The dropdown is useless to us. We need to be able to enter a PID of a fragment of a project name much as the other fields allow.

**Comment by pbchase** [comment]
@ChemiKyle I'm gonna merge this and make a new issue for the search performance complaint

**Comment by pbchase** [comment]
@tlstoffs @ChemiKyle I just deployed this feature. sorry for the massive delay

**Pull request merged**
